before_commands:
    - "composer update --prefer-source --ignore-platform-reqs"

checks:
    php:
        custom_coding_standard:
            ruleset_path: 'phpcs.xml'
        no_debug_code: true
        avoid_aliased_php_functions: true
        instanceof_class_exists: false
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        verify_property_names: true
        verify_access_scope_valid: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_methods: true
        unreachable_code: true
        switch_fallthrough_commented: true
        return_doc_comments: true
        fix_use_statements:
            remove_unused: true
            order_alphabetically: true
        code_rating: true
        avoid_unnecessary_concatenation: true

tools:
    external_code_coverage:
        timeout: 1800
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
    php_cpd:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_cs_fixer:
        enabled: false
    php_loc:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "test/*"]
    sensiolabs_security_checker: true
